image:
  repository: ""
  pullPolicy: Always
  tag: ""

imagePullSecrets: [name: regcred]

container:
  port: 5000

service:
  port: 5000


liveness:
  path: /health
  port: 5000
  initialDelaySeconds: 25
  periodSeconds: 5
readiness:
  path: /ready
  port: 5000
  initialDelaySeconds: 25
  periodSeconds: 5
