image:
  repository: ""
  pullPolicy: Always
  tag: ""

imagePullSecrets: [name: regcred]

container:
  port: 5000

service:
  type: LoadBalancer
  port: 5000

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: github.action-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - github.action-example.local

liveness:
  path: /
  port: 5000
  initialDelaySeconds: 25
  periodSeconds: 5
readiness:
  path: /
  port: 5000
  initialDelaySeconds: 25
  periodSeconds: 5
