image:
  repository: ""
  pullPolicy: Always
  tag: ""

imagePullSecrets: [name: regcred]

container:
  port: 5000

service:
  port: 5000

probes: #{}
  livenessProbe:
    httpGet:
      path: /health
      port: 5000
    initialDelaySeconds: 30
    periodSeconds: 5
  readinessProbe:
    httpGet:
      path: /ready
      port: 5000
    initialDelaySeconds: 30
    periodSeconds: 5
