repositories:
  - name: generic
    url: https://arulkumarkandasamy.github.io/helm-chart-repo/

  - name: monochart1
    url: https://arulkumarkandasamy.github.io/monochart/



# environments:
#   default:
#     values:
#       - platform:
#           region: us-east-2
#           default_ingress_domain: example.com
#           default_alb_ingress_group: default
#   preview:
#   staging:
#   production:
#   dev:
#   qa1:
#   qa2:
#   qa3:
#   qa4:
#   hotfix:

releases:
  - name: "python-dep"
    chart: "generic/gen-chart"
    createNamespace: true
    # wait: true
    # atomic: true
    # values:
    #   - ./values/pythonapp.yaml
    values:
      - image:
          repository: {{ requiredEnv "IMAGE_NAME" }}
          tag: {{ requiredEnv "IMAGE_TAG" }}
        replicaCount: 1
        imagePullSecrets: [name: regcred]

  - name: "nginx"
    chart: "monochart1/monochart"
    createNamespace: true
    # wait: true
    # atomic: true
    values:
      - ./values/nginxapp.yaml    
      - image:
          repository: nginx
          tag: latest
          pullPolicy: Always
