  name: Pull Request
  on:
    pull_request:
      branches: [ 'main' ]
      types: [opened, synchronize, reopened]

  permissions:
    id-token: write # required to use OIDC authentication
    contents: read # required to checkout the code from the repo

  jobs:
    deploy:
      runs-on: ubuntu-latest
      environment:
        name: preview
        url: ${{ steps.deploy.outputs.webapp-url }}  
      steps:
        
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1.7.0
          with:
            aws-region: eu-west-2
            role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
            role-session-name: deploy

        - name: Update Kubeconfig
          run: |
            aws eks update-kubeconfig --name eks-dev --region eu-west-2 --role-arn ${{ secrets.ROLE_TO_ASSUME }}
      
        - name: Deploy
          uses: cloudposse/github-action-deploy-helmfile@main
          id: deploy
          with:
            aws-region: eu-west-2
            cluster: eks-dev
            environment: preview
            namespace: preview
            image: nginx
            image-tag: latest
            operation: deploy
            debug: false