  name: Pull Request
  on:
    pull_request:
      branches: [ 'main' ]
      types: [opened, synchronize, reopened]

  permissions:
    id-token: write # required to use OIDC authentication
    contents: read # required to checkout the code from the repo

  jobs:
    deploy:
      runs-on: ubuntu-latest
      environment:
        name: dev
        url: ${{ steps.deploy.outputs.webapp-url }}  
      steps:

        - name: Checkout repository
          uses: actions/checkout@v3
        
        - name: AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-2
      
        - name: Deploy
          uses: cloudposse/github-action-deploy-helmfile@main
          id: deploy
          with:
            aws-region: eu-west-2
            cluster: eks-dev
            environment: dev
            namespace: dev
            helmfile-path: deploy/helmfile
            image: nginx
            image-tag: latest
            operation: deploy
            debug: false