  name: Pull Request
  on:
    pull_request:
      branches: [ 'main' ]
      types: [opened, synchronize, reopened]

  permissions:
    id-token: write # required to use OIDC authentication
    contents: read # required to checkout the code from the repo

  env:
    REGISTRY: ghcr.io
    #IMAGE_NAME: ${{ needs.build.outputs.image }}
    #IMAGE_TAG: ${{ needs.build.outputs.tag }}

  jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:

        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Check
          run: |
            echo "${{ github.event.repository.owner.login }}"
            echo "${{ github.event.repository.name }}"
            echo "${{ needs.build.outputs.image }}"
            echo "${{ needs.build.outputs.image }}"

        - name: Log in to the Container registry
          uses: docker/login-action@v2.1.0
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Docker build publish
          uses: cloudposse/github-action-docker-build-push@main
          id: build
          with:
            workdir: ./app
            registry: ${{ env.REGISTRY }}
            organization: "${{ github.event.repository.owner.login }}"
            repository: "python"
            login: ${{ github.actor }}
            password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

        
        - name: AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-west-2
      
        - name: Deploy
          uses: cloudposse/github-action-deploy-helmfile@main
          id: deploy
          with:
            aws-region: eu-west-2
            cluster: eks-dev
            environment: dev
            namespace: dev
            helmfile-path: deploy
            image: nginx
            image-tag: latest
            operation: deploy
            debug: false